# -*- coding: utf-8 -*-
from odoo import models, fields, api, _
import json
import hashlib

class CaqaScoreSnapshot(models.Model):
    _name = 'caqa.score.snapshot'
    _description = 'Evaluation Frozen Snapshot'
    _order = 'generated_at desc'

    application_id = fields.Many2one('caqa.application', string='Application', required=True, ondelete='cascade')
    cycle_id = fields.Many2one('caqa.score.cycle', string='Cycle', required=True, ondelete='cascade')
    
    snapshot_data = fields.Text(string='Snapshot JSON Data', required=True, readonly=True, 
                                help="Immutable JSON structure of the scores, rubrics, and weights at the time of freezing.")
    
    generated_at = fields.Datetime(string='Generated At', default=fields.Datetime.now, readonly=True)
    generated_by = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user, readonly=True)
    checksum = fields.Char(string='Checksum Hash', readonly=True, copy=False)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if 'snapshot_data' in vals:
                vals['checksum'] = hashlib.sha256(vals['snapshot_data'].encode('utf-8')).hexdigest()
        return super().create(vals_list)

    def write(self, vals):
        if 'snapshot_data' in vals or 'checksum' in vals:
            raise models.ValidationError(_("Snapshots are immutable. You cannot modify the frozen data or checksum."))
        return super().write(vals)
